name: Publish to Maven Central

on:
  release:
    types: [ published ]

jobs:
  publish:
    name: Publish
    runs-on: macos-latest  # macOS necessário para compilar os targets iOS

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-disabled: true

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Publish to Maven Central
        run: ./gradlew :composeApp:publishAllPublicationsToMavenCentralRepository -x kmpPartiallyResolvedDependenciesChecker -Pandroid.useAndroidX=true --no-configuration-cache
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.OSSRH_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
